[package]
name = "mqtt-client-rust-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.12"
tokio = { version = "1", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.3"